    services:
     zabbix-server:
       image: zabbix/zabbix-server-pgsql:latest
       ports:
         - "10051:10051"
     zabbix-web:
       image: zabbix/zabbix-web-nginx-pgsql:latest
       ports:
         - "8080:8080"